backend:
  name: github
  repo: DboxDev/cibcsquare-baypark-website   # Path to your Github repository
  branch: develop              # Branch to update
  base_url: https://bayparkcentre-auth.dbxd.com

media_folder: "assets/images/uploads" # Media files will be stored in the repo here
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Optional PDF", name: "pdf", widget: "file", required: false}
      - {label: "Body", name: "body", widget: "markdown"}